cluster_name: demo.mapr.com
customer_name: MapR PS
output_dir: /Users/chufe/clustercheck
mapr_user: mapr

nodes:
  - host: 10.0.0.24
    ssh_user: ec2-user
    ssh_identity: '/Users/chufe/.ssh/id_rsa'
    roles:
       - datacenter1
       - clusterjob-execution
  - host: 10.0.0.167
    ssh_user: ec2-user
    ssh_identity: '/Users/chufe/.ssh/id_rsa'
    roles:
      - datacenter1
  - host: 10.0.0.239
    ssh_user: ec2-user
    ssh_identity: '/Users/chufe/.ssh/id_rsa'
    roles:
      - datacenter1

modules:
  clusteraudit:
    enabled: true
    role: datacenter1
  benchmark-network-iperf:
    enabled: true
    tests:
    - threads: 1
      data_per_thread: 4096M
  benchmark-maprfs-dfsio:
    enabled: true
    dfsio_files_per_disk: 1
    dfsio_file_size_in_mb: 8196
    role: clusterjob-execution
  benchmark-maprfs-rwtest:
    enabled: true
    tests:
    - volume_type: standard
      compression: 'off'
      topology: /data
      size_in_mb: 256
      threads: 3
      replication: 3
    - volume_type: standard
      compression: 'on'
      topology: /data
      size_in_mb: 256
      threads: 3
      replication: 3
    - volume_type: local
      compression: 'off'
      size_in_mb: 256
    - volume_type: local
      compression: 'on'
      size_in_mb: 256
  benchmark-yarn-terasort-mr:
    enabled: true
    role: clusterjob-execution
    chunk_size_in_mb: 256
    rows: 5000000
    reduce_tasks_per_node: 2
    topology: /data
    replication: 3
  benchmark-yarn-terasort-spark:
    enabled: true
    role: clusterjob-execution
    chunk_size_in_mb: 256
    data_size: 1G
    num_executors: 6
    executor_cores: 2
    executor_memory: 2G
    topology: /data
    replication: 3
    compression: 'on'
