cluster_name: demo.mapr.com
customer_name: Your company name
output_dir: /path/for/results
mapr_user: mapr
nodes:
- host: hostname1.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
  roles:
  - clusterjob-execution
- host: hostname2.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
- host: hostname3.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
modules:
  clusteraudit:
    enabled: true
  benchmark-network-iperf:
    enabled: true
    tests:
    - threads: 1
      data_per_thread: 4096M
    - threads: 2
      data_per_thread: 2048M
    - threads: 4
      data_per_thread: 1024M
    - threads: 8
      data_per_thread: 512M
  benchmark-maprfs-dfsio:
    enabled: true
    role: clusterjob-execution
    dfsio_files_per_disk: 1
    dfsio_file_size_in_mb: 8196
    topology: /data
    replication: 1
    compression: 'on'
  benchmark-maprfs-rwtest:
    enabled: true
    tests:
    - volume_type: standard
      compression: 'off'
      topology: /data
      size_in_mb: 16384
      replication: 3
      threads: 1
    - volume_type: standard
      compression: 'on'
      topology: /data
      size_in_mb: 16384
      replication: 3
      threads: 1
    - volume_type: local
      compression: 'off'
      use_disk_percentage: 5
    - volume_type: local
      compression: 'on'
      use_disk_percentage: 5
  benchmark-yarn-terasort-mr:
    enabled: true
    role: clusterjob-execution
    chunk_size_in_mb: 256
    rows: 10000000000
    rows_comment: one row has 100 byte
    reduce_tasks_per_node: 2
    topology: /data
    replication: 3
    compression: 'on'
  benchmark-yarn-terasort-spark:
    enabled: true
    role: clusterjob-execution
    chunk_size_in_mb: 256
    data_size: 1T
    num_executors: 10
    executor_cores: 2
    executor_memory: 4G
    topology: /data
    replication: 3
    compression: 'on'
